#!/bin/bash
#set -ex
file="/tmp/zamanligorevcommand"
while true; do
        #echo "."
        if [ -f ${file} ]
                then
                        komut=$(cat ${file})
                        #echo "çalışacak komut ${komut}"
                        ${komut}
                        #source ${file}
                        rm -rf ${file}
                fi
        sleep 5
done

